root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./backend/cmd/server"
  entrypoint = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "gen"]
  delay = 100

[log]
  time = true

[misc]
  clean_on_exit = true
