// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Todo struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Completed bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID          uuid.UUID
	Email       string
	GoogleID    sql.NullString
	DisplayName string
	AvatarUrl   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
