// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, google_id, display_name, avatar_url, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByGoogleID = `-- name: UpsertUserByGoogleID :one
INSERT INTO users (email, google_id, display_name, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (google_id) DO UPDATE
  SET email        = EXCLUDED.email,
      display_name = EXCLUDED.display_name,
      avatar_url   = EXCLUDED.avatar_url,
      updated_at   = now()
RETURNING id, email, google_id, display_name, avatar_url, created_at, updated_at
`

type UpsertUserByGoogleIDParams struct {
	Email       string
	GoogleID    sql.NullString
	DisplayName string
	AvatarUrl   string
}

func (q *Queries) UpsertUserByGoogleID(ctx context.Context, arg UpsertUserByGoogleIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUserByGoogleID,
		arg.Email,
		arg.GoogleID,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
