name: Renovate

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      # GitHub AppからInstallation Tokenを生成
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v3.2.0
        with:
          app-id: ${{ secrets.MY_RENOVATE_APP_ID }}
          private-key: ${{ secrets.MY_RENOVATE_APP_PRIVATE_KEY }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.17
        with:
          token: ${{ steps.generate-token.outputs.token }}
          configurationFile: renovate.json
          renovate-version: 43.129.0
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
